DROP TABLE IF EXISTS Paesaggi CASCADE;

CREATE TABLE Paesaggi(
	id serial PRIMARY KEY,
	url varchar(100),
	categoria1 varchar(20), --nome
	valorecorretto2 varchar(30), --nomecorretto
	valoreerrato10 varchar(30), --opzione nome 1
	valoreerrato11 varchar(30), --opzione nome 2
	valoreerrato12 varchar(30), --opzione nome 3
	valoreerrato13 varchar(30), --opzione nome 4
	categoria2 varchar(30), --nazionediappartenenza
	valorecorretto3 varchar(30), --nazionediappartenenzacorretto
	valoreerrato20 varchar(30), --opzione nazionediappartenenza 1
	valoreerrato21 varchar(30), --opzione nazionediappartenenza 2
	valoreerrato22 varchar(30), --opzione nazionediappartenenza 3
	valoreerrato23 varchar(30) --opzione nazionediappartenenza 4
);


insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio1.jpg', 'Nome:', 'Atene', 'Isola di Pasqua', 'New York', 'Dubai', 'Atene', 'Nazione di appartenenza:', 'Grecia', 'Islanda' , 'Italia', 'Francia', 'Grecia');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio2.jpg', 'Nome:', 'Aurora boreale', 'Cascate del Niagara', 'Grand Canyon', 'Monte Bianco', 'Aurora boreale', 'Nazione di appartenenza:', 'Norvegia', 'Islanda' , 'Finlandia', 'Giappone', 'Norvegia');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio3.jpg', 'Nome:', 'Barriera corallina', 'Dubai', 'Isola di Pasqua', 'Oceano antartico', 'Barriera corallina', 'Nazione di appartenenza:', 'Queensland', 'Stati Uniti' , 'Hawaii', 'Giappone', 'Queensland');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio4.jpg', 'Nome:', 'Cascate del Niagara', 'Isola di Pasqua', 'Monte Fuji', 'Geyser', 'Cascate del Niagara', 'Nazione di appartenenza:', 'Stati Uniti', 'Italia' , 'Giappone', 'Cile', 'Stati Uniti');

insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio5.jpg', 'Nome:', 'Deserto del Sahara', 'Deserto del Sinai', 'Deserto della Patagonia', 'Deserto di Thar', 'Deserto del Sahara', 'Nazione di appartenenza:', 'Sahara', 'Egitto' , 'Emirati Arabi', 'Giappone', 'Sahara');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio6.jpg', 'Nome:', 'Dubai', 'Parigi', 'Roma', 'New York', 'Dubai', 'Nazione di appartenenza:', 'Emirati Arabi', 'Stati Uniti' , 'Francia', 'Italia', 'Emirati Arabi');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio7.jpg', 'Nome:', 'Geyser', 'Cascate del Niagara', 'Oceano antartico', 'Barriera corallina', 'Geyser', 'Nazione di appartenenza:', 'Islanda', 'Queensland' , 'Stati Uniti', 'Antartide', 'Islanda');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio8.jpg', 'Nome:', 'Grand Canyon', 'Grande muraglia', 'Monte Bianco', 'Deserto del Sahara', 'Grand Canyon', 'Nazione di appartenenza:', 'Stati Uniti', 'Giappone' , 'Cina', 'Francia', 'Stati Uniti');

insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio9.jpg', 'Nome:', 'Grande muraglia', 'Grand Canyon', 'Monte Bianco', 'Hawaii', 'Grande muraglia', 'Nazione di appartenenza:', 'Cina', 'Stati Uniti' , 'Italia', 'Grecia', 'Cina');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio10.jpg', 'Nome:', 'Hawaii', 'Isola di Pasqua', 'Barriera corallina', 'Dubai', 'Hawaii', 'Nazione di appartenenza:', 'Stati Uniti', 'Emirati Arabi' , 'Cile', 'Queensland', 'Stati Uniti');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio11.jpg', 'Nome:', 'Isola di Pasqua', 'Dubai', 'Deserto del Sinai', 'Stonehenge', 'Isola di Pasqua', 'Nazione di appartenenza:', 'Cile', 'Regno Unito' , 'Egitto', 'Italia', 'Cile');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio12.jpg', 'Nome:', 'Monte Bianco', 'Isola di Pasqua', 'Monte Cimone', 'Cima del Redentore', 'Monte Bianco', 'Nazione di appartenenza:', 'Italia', 'Islanda' , 'Finlandia', 'Norvegia', 'Italia');

insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio13.jpg', 'Nome:', 'Monte Fuji', 'Monte Bianco', 'Monte Cimone', 'Vesuvio', 'Monte Fuji', 'Nazione di appartenenza:', 'Giappone', 'Norvegia' , 'Italia', 'Cina', 'Giappone');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio14.jpg', 'Nome:', 'New York', 'Chicago', 'Boston', 'Londra', 'New York', 'Nazione di appartenenza:', 'Stati Uniti', 'Islanda' , 'Regno Unito', 'Emirati Arabi', 'Stati Uniti');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio15.jpg', 'Nome:', 'Oceano antartico', 'Oceano indiano', 'Oceano atlantico', 'Oceano pacifico', 'Oceano antartico', 'Nazione di appartenenza:', 'Antartide', 'Islanda' , 'Danimarca', 'Finlandia', 'Antartide');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio16.jpg', 'Nome:', 'Parco di Nara', 'Central Park', 'Hyde Park', 'Yellowstone National Park', 'Parco di Nara', 'Nazione di appartenenza:', 'Giappone', 'Regno Unito' , 'Stati Uniti', 'Olanda', 'Giappone');

insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio17.jpg', 'Nome:', 'Parigi', 'Londra', 'Roma', 'Lione', 'Parigi', 'Nazione di appartenenza:', 'Francia', 'Egitto' , 'Emirati Arabi', 'Italia', 'Francia');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio18.jpg', 'Nome:', 'Sfinge', 'Isola di Pasqua', 'Stonehenge', 'Dubai', 'Sfinge', 'Nazione di appartenenza:', 'Egitto', 'Emirati Arabi' , 'Regno Unito', 'Cile', 'Egitto');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio19.jpg', 'Nome:', 'Stonehenge', 'Roma', 'Atene', 'Isola di Pasqua', 'Stonehenge', 'Nazione di appartenenza:', 'Regno Unito', 'Grecia' , 'Italia', 'Cina', 'Regno Unito');
insert into Paesaggi(url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('Immagini/paesaggi/paesaggio20.jpg', 'Nome:', 'Vesuvio', 'Monte Bianco', 'Monte Fuji', 'Cima del Redentore', 'Vesuvio', 'Nazione di appartenenza:', 'Italia', 'Giappone' , 'Italia', 'Francia', 'Italia');

select * from paesaggi;
