DROP TABLE IF EXISTS Personaggi CASCADE;

CREATE TABLE Personaggi(
	id serial PRIMARY KEY,
	url VARCHAR(100),
	categoria1 varchar(40),     --nome del personaggio:
	valorecorretto2 varchar(40),--nome corretto:
	valoreerrato10 varchar(40), --opzione nome 1:
	valoreerrato11 varchar(40), --opzione nome 2:
	valoreerrato12 varchar(40), --opzione nome 3:
	valoreerrato13 varchar(40), --opzione nome 4:
	categoria2 varchar(40),     --nome del cartone:
	valorecorretto3 varchar(40),--nome corretto:
	valoreerrato20 varchar(40), --opzione nome cartone 1:
	valoreerrato21 varchar(40), --opzione nome cartone 2:
	valoreerrato22 varchar(40), --opzione nome cartone 3:
	valoreerrato23 varchar(40)  --opzione nome cartone 4:
);

insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/margot-lupin.jpg', 'Nome del personaggio:', 'Margot', 'Maria Fleed', 'Minami','Atsuko', 'Margot', 'Nome del cartone:', 'LupinIII', 'Lupin', 'Lamù', 'Georgie', 'LupinIII');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/atlas_ufo_robot_goldrake.jpg', 'Nome del personaggio:', 'Atlas', 'Ryo', 'Hiroshi Shiba', 'capitan harlock', 'Atlas', 'Nome del cartone:', 'ufo robot goldrake', 'jeeg Robot d''acciaio', 'capitan harlock', 'Georgie', 'ufo robot goldrake');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/Ben_10_2x2.jpg', 'Nome del personaggio:', '2x2', 'Bisbraccio', '4x4', 'Muscle Red', '2x2', 'Nome del cartone:', 'Ben 10', 'Ban 100' , 'Omnitrix' , 'Super alien', 'Ben 10');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/Betty-Boop_betty_boop.jpg', 'Nome del personaggio:', 'Betty Boop', 'Lamù', 'Georgie', 'Marlù', 'Betty Boop', 'Nome del cartone:', 'Betty-Boop' , 'Bugie-Boop', 'Fashion', 'Dance Girl', 'Betty-Boop');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/c-16_Dragonball_z.jpg', 'Nome del personaggio:', 'C-16', 'B-12', 'C-17', 'B-18', 'C-16', 'Nome del cartone:', 'Dragonball z', 'Dragonball GT', 'Dragonball super', 'Dragon-man', 'Dragonball z');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23) values('immagini/Personaggi_Animati/Detective-Conan_conan.jpg', 'Nome del personaggio:', 'Conan', 'Sherlock', 'lelouch', 'sharlock', 'Conan', 'Nome del cartone:', 'Detective Conan', 'il fiuto di Sherlock Holmes', 'Code Geass', 'Conan', 'Detective Conan');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/Finn_adventure_time.jpg', 'Nome del personaggio:', 'Finn', 'Jake' , 'Fill', 'Mill', 'Finn', 'Nome del cartone:', 'Adventure Time', 'Adventure Guy', 'Adeventure Boy', 'Adventure Dog', 'Adventure Time');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/Garfield_Garfield.jpg', 'Nome del personaggio:', 'Garfield','Garfid', 'cat', 'Garbin', 'Garfield', 'Nome del cartone:', 'Garfield', 'Garfid', 'catfield', 'Garbin', 'Garfield');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/Kakashi_naruto_.jpg', 'Nome del personaggio:', 'Kakashi', 'Obito','Madara', 'Inuyasha', 'Kakashi', 'Nome del cartone:', 'Naruto', 'Samurai', 'Inuyasha', 'Uzumaki', 'Naruto');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/kid_muscle_Ultimate_muscle.jpg', 'Nome del personaggio:', 'Kid Muscle', 'King Muscle', 'Fight Boy', 'Wrester King', 'Kid Muscle', 'Nome del cartone:', 'Ultimate Muscle', 'Muscle WW', 'Wrestling', 'Muscle Fight', 'Ultimate Muscle');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/kira_Death_note.jpg', 'Nome del personaggio:', 'Kira', 'Leoluch', 'Elle', 'Near', 'Kira', 'Nome del cartone:', 'Death Note', 'Code Geass', 'Shinigami', 'Tokyo Ghoul', 'Death Note');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/le-bizzarre-avventure-di-jojo-joseph-joestar-v3-420357.jpg', 'Nome del personaggio:', 'Joseph Joestar', 'Jonathan Joestar', 'Jotaro Kujo', 'Giorno Giovanna', 'Joseph Joestar', 'Nome del cartone:', 'Le bizzarre avventure di jojo', 'Vite bizzarre di gente eccentrica', 'Jolyne fly high with Gucci', 'Le bizzarre avventure con jojo', 'Le bizzarre avventure di jojo');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/marilù_leone_cane_fifone.jpg', 'Nome del personaggio:', 'Marilù', 'Giustina', 'Nicole', 'Nailù', 'Marilù', 'Nome del cartone:', 'Leone il cane fifone', 'Leone cane fifone', 'Scooby Doo', 'Schooby Doo', 'Leone il cane fifone');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/phineas-e-ferb_candace.jpg', 'Nome del personaggio:', 'Candace', 'Candice', 'Isabella', 'Vanessa', 'Candace', 'Nome del cartone:', 'Phineas e Ferb', 'Fineas e Ferb', 'Griffin', 'le incredibili avventure di Rick e Morty', 'Phineas e Ferb');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/Rufy_one_piece.jpg', 'Nome del personaggio:', 'Rufy', 'rubber', 'Zoro', 'Sanji', 'Rufy', 'Nome del cartone:', 'One Piece', 'Naruto', 'Inuyasha', 'Bleach', 'Rufy');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/sasha_attack_on_titan.jpg', 'Nome del personaggio:', 'Sasha', 'Annie', 'Hanji', 'Ymir', 'Sasha', 'Nome del cartone:', 'Shingeki no kyojin', 'Attacco dai giganti', 'Gigant Attack', 'teen Titans', 'Shingeki no kyojin');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/stich_lilo-e-stitch.jpg', 'Nome del personaggio:', 'Stitch', 'Lilo', 'Nani', 'Stich', 'Stitch', 'Nome del cartone:', 'Lilo e Stitch', 'Lilo e Stich', 'Gormiti', 'Alien', 'Lilo e Stitch');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/tokyo-ghoul-ken-kaneki.jpg', 'Nome del personaggio:', 'Ken Kaneki', 'Yashiro', 'Bakugou', 'Levi', 'Ken Kaneki', 'Nome del cartone:', 'Tokyo Ghoul', 'K', 'My hero Academia', 'My hero Accademy', 'Tokyo Ghoul');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/Winnie_Pooh_Winnie_Pooh.jpg', 'Nome del personaggio:', 'Winnie the Pooh', 'Tigro', 'Pimpi', 'Winnie Pooh', 'Winnie the Pooh', 'Nome del cartone:', 'Winnie the Pooh', 'Winnie Pooh', 'Winny Pooh', 'Winni th Poo', 'Winnie the Pooh');
insert into Personaggi (url, categoria1, valorecorretto2, valoreerrato10 , valoreerrato11 , valoreerrato12, valoreerrato13, categoria2, valorecorretto3 , valoreerrato20 , valoreerrato21, valoreerrato22, valoreerrato23)values('immagini/Personaggi_Animati/yugi_yu-gi-oh.jpg', 'nome del personaggio:', 'yugi', 'Mai', 'Seto', 'Ryo', 'yugi', 'Nome del cartone:', 'yu-gi-oh', 'yugi oh', 'yugioh', 'yu gioh', 'yu-gi-oh');


select * from personaggi;